server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/makerspacetest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  security:
    user:
    name: admin
    password: admin

  jpa:
    showSql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
    cache: false


  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

mybatis:
  type-aliases-package: com.sise.makerSpace.domain
  mapper-locations: classpath:/mapperXml/*.xml

#debug: true